<div class="head clear">
	<a href="/" id="hero-image" title="Mindfulness Training Institute Australasia">
		<img src="/media/img/mti_logo_web.png" title="Mindfulness Training Institute Australasia" alt="Mindfulness Training Institute Australasia" id="logo" />
	</a>	
	{% include "/_System/Includes/social-menu.inc" -%}
	{module_menu, version="2", menuId="1639146", moduleTemplateGroup="Top Menu"}
</div>